[package]
name = "voice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
cpal = "0.14.0"
hound = "3.5.1"
itertools = "0.12.1"
linfa = "0.7.0"
thiserror = "1.0.58"
webrtc-vad = "0.4.0"
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", branch = "master", features = [ "coreml", "whisper-cpp-log" ] }
sttx = { git = "file:///Users/matt/code/lang/rust/sttx", branch = "main" }
clap = { version = "4.5.4", features = ["derive"] }
