[package]
name = "voice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
cpal = "0.15.3"
hound = "3.5.1"
linfa = "0.7.0"
webrtc-vad = "0.4.0"
# whisper-rs = { version = "0.10.0", features = ["coreml", "metal"] }
